### ISSUE TITLE
Node 8.x locked out because `fs-extra` syntax error

### ISSUE THREAD

**Issue by marcolovescode** [marcolovescode/emscripten-build-npm#18]
See [AppVeyor build](https://ci.appveyor.com/project/mazmazz/emscripten-build-npm/builds/36511154/job/wtknto08h2inlkdy)

This only affects the `cmake-binaries` dependency, which if the system already has CMake installed, then the build system works as normal.

```
> cmake-binaries@1.0.0 install /Users/appveyor/emscripten-npm-examples/Example-04-CMake/node_modules/cmake-binaries
> node ./src/install.js
/Users/appveyor/emscripten-npm-examples/Example-04-CMake/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/appveyor/emscripten-npm-examples/Example-04-CMake/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

**Comment by marcolovescode** [comment]
I made this fork to resolve this syntax issue, but there are other errors, see #19

https://github.com/jprichardson/node-fs-extra/compare/master...marcolovescode:catch-identifiers?expand=1

**Comment by marcolovescode** [comment]
Per LTS schedule, don't support anything older than Node 10.x
